import {PGlite} from '@electric-sql/pglite';import{readFileSync}from'node:fs';import assert from'node:assert/strict';
const db=new PGlite();await db.exec(`CREATE ROLE anon; CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE SCHEMA storage;CREATE SCHEMA extensions;
CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql AS $$ SELECT coalesce(nullif(current_setting('test.jwt',true),''),'{}')::jsonb $$;
CREATE FUNCTION extensions.digest(text,text) RETURNS bytea LANGUAGE sql IMMUTABLE AS $$ SELECT convert_to($1,'UTF8') $$;
CREATE TABLE storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
CREATE TABLE storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb,created_at timestamptz default now());ALTER TABLE storage.objects ENABLE ROW LEVEL SECURITY;GRANT USAGE ON SCHEMA public,storage,auth TO anon,authenticated;GRANT SELECT,INSERT ON storage.objects TO anon,authenticated;`);
let sql=readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8').replace('create extension if not exists pgcrypto with schema extensions;','');await db.exec(sql);await db.exec(`INSERT INTO public.officers VALUES ('allowed@example.test',ARRAY['bma-1']),('all@example.test',ARRAY['*']);`);
const token='a'.repeat(64);await db.exec('SET ROLE anon');const args=['00000000-0000-4000-8000-000000000001',token,'bma-1','ทดสอบ','0812345678','test@example.test','ทดสอบเหตุการณ์'];let r=await db.query('SELECT public.submit_case($1,$2,$3,$4,$5,$6,$7) AS id',args);let id=r.rows[0].id;assert.match(id,/^CASE-\d{4}-\d{6}$/);
r=await db.query('SELECT public.submit_case($1,$2,$3,$4,$5,$6,$7) AS id',args);assert.equal(r.rows[0].id,id);
await assert.rejects(db.query('select * from public.cases'),/permission denied/);await assert.rejects(db.query('select public.officer_cases($1)',['bma-1']),/permission denied/);await assert.rejects(db.query('select public.track_case($1,$2)',[id,'b'.repeat(64)]),/รหัสติดตาม/);
r=await db.query('select public.track_case($1,$2) as data',[id,token]);assert.equal(r.rows[0].data.status,'verifying');assert.equal(r.rows[0].data.name,undefined);
await db.exec("RESET ROLE;SET ROLE authenticated;SET test.jwt='{\"email\":\"allowed@example.test\"}';");await assert.rejects(db.query('select public.officer_cases($1)',['bma-2']),/ไม่มีสิทธิ์/);
await assert.rejects(db.query('select public.update_case($1,0,$2,$3,$4)',[id,'additional_info','','']),/กรุณาระบุ/);
await db.query('select public.update_case($1,0,$2,$3,$4)',[id,'additional_info','ขอเอกสาร','ทะเบียนรถ']);await assert.rejects(db.query('select public.update_case($1,0,$2,$3,$4)',[id,'completed','','']),/ถูกแก้ไข/);
await db.exec('RESET ROLE;SET ROLE anon');await db.query('select public.reply_case($1,$2,$3)',[id,token,'ส่งข้อมูลเพิ่ม']);
await assert.rejects(db.query("INSERT INTO storage.objects(bucket_id,name) VALUES('case-documents',$1)",[id+'/bad/file/test.pdf']),/row-level/);
await db.query("INSERT INTO storage.objects(bucket_id,name,metadata) VALUES('case-documents',$1,'{\"size\":123}')",[id+'/'+token+'/file/test.pdf']);r=await db.query('SELECT * FROM storage.objects');assert.equal(r.rows.length,0);
await db.exec("RESET ROLE;SET ROLE authenticated;SET test.jwt='{\"email\":\"allowed@example.test\"}';");r=await db.query('select public.officer_case($1) as data',[id]);assert.equal(r.rows[0].data.attachments.length,1);assert.equal(r.rows[0].data.history.length,3);assert.equal(r.rows[0].data.case.token_hash,undefined);
console.log('PASS: schema, shared case ID, duplicate retry, anonymous restrictions, station isolation, required information, optimistic locking, applicant reply, private file upload/read and audit history. Digest is stubbed in this local harness; production uses pgcrypto.');await db.close();
